---
services:
  demon_pear:
    build: .
    image: mt1976/frantic-aliquid:latest
    container_name: demon_pear
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/matttownsend/Docker/demon_pear/backups:/app/data/backups
      - /Users/matttownsend/Docker/shared/database:/app/data/database
      - /Users/matttownsend/Docker/demon_pear/dumps:/app/data/dumps
      - /Users/matttownsend/Docker/shared/logs:/app/data/logs
      - /Users/matttownsend/Docker/demon_pear/defaults:/app/data/defaults
    ports:
      - 5052:5052
    restart: unless-stopped